//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoOcho.WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="https://www.intec.edu.do/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="https://www.intec.edu.do/")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        private int TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.intec.edu.do/", ConfigurationName="WS.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace https://www.intec.edu.do/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.intec.edu.do/HelloWorld", ReplyAction="*")]
        DemoOcho.WS.HelloWorldResponse HelloWorld(DemoOcho.WS.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.intec.edu.do/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<DemoOcho.WS.HelloWorldResponse> HelloWorldAsync(DemoOcho.WS.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.intec.edu.do/Sumar", ReplyAction="*")]
        int Sumar(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.intec.edu.do/Sumar", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SumarAsync(int n1, int n2);
        
        // CODEGEN: Generating message contract since element name cliente from namespace https://www.intec.edu.do/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.intec.edu.do/RegistrarCliente", ReplyAction="*")]
        DemoOcho.WS.RegistrarClienteResponse RegistrarCliente(DemoOcho.WS.RegistrarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.intec.edu.do/RegistrarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<DemoOcho.WS.RegistrarClienteResponse> RegistrarClienteAsync(DemoOcho.WS.RegistrarClienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="https://www.intec.edu.do/", Order=0)]
        public DemoOcho.WS.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(DemoOcho.WS.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="https://www.intec.edu.do/", Order=0)]
        public DemoOcho.WS.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(DemoOcho.WS.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.intec.edu.do/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarCliente", Namespace="https://www.intec.edu.do/", Order=0)]
        public DemoOcho.WS.RegistrarClienteRequestBody Body;
        
        public RegistrarClienteRequest() {
        }
        
        public RegistrarClienteRequest(DemoOcho.WS.RegistrarClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.intec.edu.do/")]
    public partial class RegistrarClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DemoOcho.WS.Cliente cliente;
        
        public RegistrarClienteRequestBody() {
        }
        
        public RegistrarClienteRequestBody(DemoOcho.WS.Cliente cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarClienteResponse", Namespace="https://www.intec.edu.do/", Order=0)]
        public DemoOcho.WS.RegistrarClienteResponseBody Body;
        
        public RegistrarClienteResponse() {
        }
        
        public RegistrarClienteResponse(DemoOcho.WS.RegistrarClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.intec.edu.do/")]
    public partial class RegistrarClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DemoOcho.WS.Respuesta RegistrarClienteResult;
        
        public RegistrarClienteResponseBody() {
        }
        
        public RegistrarClienteResponseBody(DemoOcho.WS.Respuesta RegistrarClienteResult) {
            this.RegistrarClienteResult = RegistrarClienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : DemoOcho.WS.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<DemoOcho.WS.WebService1Soap>, DemoOcho.WS.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoOcho.WS.HelloWorldResponse DemoOcho.WS.WebService1Soap.HelloWorld(DemoOcho.WS.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            DemoOcho.WS.HelloWorldRequest inValue = new DemoOcho.WS.HelloWorldRequest();
            inValue.Body = new DemoOcho.WS.HelloWorldRequestBody();
            DemoOcho.WS.HelloWorldResponse retVal = ((DemoOcho.WS.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DemoOcho.WS.HelloWorldResponse> DemoOcho.WS.WebService1Soap.HelloWorldAsync(DemoOcho.WS.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<DemoOcho.WS.HelloWorldResponse> HelloWorldAsync() {
            DemoOcho.WS.HelloWorldRequest inValue = new DemoOcho.WS.HelloWorldRequest();
            inValue.Body = new DemoOcho.WS.HelloWorldRequestBody();
            return ((DemoOcho.WS.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Sumar(int n1, int n2) {
            return base.Channel.Sumar(n1, n2);
        }
        
        public System.Threading.Tasks.Task<int> SumarAsync(int n1, int n2) {
            return base.Channel.SumarAsync(n1, n2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoOcho.WS.RegistrarClienteResponse DemoOcho.WS.WebService1Soap.RegistrarCliente(DemoOcho.WS.RegistrarClienteRequest request) {
            return base.Channel.RegistrarCliente(request);
        }
        
        public DemoOcho.WS.Respuesta RegistrarCliente(DemoOcho.WS.Cliente cliente) {
            DemoOcho.WS.RegistrarClienteRequest inValue = new DemoOcho.WS.RegistrarClienteRequest();
            inValue.Body = new DemoOcho.WS.RegistrarClienteRequestBody();
            inValue.Body.cliente = cliente;
            DemoOcho.WS.RegistrarClienteResponse retVal = ((DemoOcho.WS.WebService1Soap)(this)).RegistrarCliente(inValue);
            return retVal.Body.RegistrarClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DemoOcho.WS.RegistrarClienteResponse> DemoOcho.WS.WebService1Soap.RegistrarClienteAsync(DemoOcho.WS.RegistrarClienteRequest request) {
            return base.Channel.RegistrarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<DemoOcho.WS.RegistrarClienteResponse> RegistrarClienteAsync(DemoOcho.WS.Cliente cliente) {
            DemoOcho.WS.RegistrarClienteRequest inValue = new DemoOcho.WS.RegistrarClienteRequest();
            inValue.Body = new DemoOcho.WS.RegistrarClienteRequestBody();
            inValue.Body.cliente = cliente;
            return ((DemoOcho.WS.WebService1Soap)(this)).RegistrarClienteAsync(inValue);
        }
    }
}
