//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Ejercicio1Entities : DbContext
    {
        public Ejercicio1Entities()
            : base("name=Ejercicio1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCliente> tblClientes { get; set; }
        public virtual DbSet<tblMovimiento> tblMovimientos { get; set; }
    
        public virtual ObjectResult<GetCliente_Result> GetCliente(Nullable<int> tipoDocumento, string documento)
        {
            var tipoDocumentoParameter = tipoDocumento.HasValue ?
                new ObjectParameter("TipoDocumento", tipoDocumento) :
                new ObjectParameter("TipoDocumento", typeof(int));
    
            var documentoParameter = documento != null ?
                new ObjectParameter("Documento", documento) :
                new ObjectParameter("Documento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCliente_Result>("GetCliente", tipoDocumentoParameter, documentoParameter);
        }
    
        public virtual int InsertarCliente(string nombres, string apellidos, Nullable<System.DateTime> fechaNacimiento, string sexo, string comentario, Nullable<int> tipoDocumento, string documento, Nullable<decimal> balance)
        {
            var nombresParameter = nombres != null ?
                new ObjectParameter("Nombres", nombres) :
                new ObjectParameter("Nombres", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("Apellidos", apellidos) :
                new ObjectParameter("Apellidos", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(string));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("Comentario", comentario) :
                new ObjectParameter("Comentario", typeof(string));
    
            var tipoDocumentoParameter = tipoDocumento.HasValue ?
                new ObjectParameter("TipoDocumento", tipoDocumento) :
                new ObjectParameter("TipoDocumento", typeof(int));
    
            var documentoParameter = documento != null ?
                new ObjectParameter("Documento", documento) :
                new ObjectParameter("Documento", typeof(string));
    
            var balanceParameter = balance.HasValue ?
                new ObjectParameter("Balance", balance) :
                new ObjectParameter("Balance", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarCliente", nombresParameter, apellidosParameter, fechaNacimientoParameter, sexoParameter, comentarioParameter, tipoDocumentoParameter, documentoParameter, balanceParameter);
        }
    
        public virtual int InsertarMovimiento(Nullable<int> tipoDocumento, string documento, Nullable<decimal> monto, string dbCredito, Nullable<int> tipoTransaccion, string descripcion, string oficina)
        {
            var tipoDocumentoParameter = tipoDocumento.HasValue ?
                new ObjectParameter("TipoDocumento", tipoDocumento) :
                new ObjectParameter("TipoDocumento", typeof(int));
    
            var documentoParameter = documento != null ?
                new ObjectParameter("Documento", documento) :
                new ObjectParameter("Documento", typeof(string));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(decimal));
    
            var dbCreditoParameter = dbCredito != null ?
                new ObjectParameter("DbCredito", dbCredito) :
                new ObjectParameter("DbCredito", typeof(string));
    
            var tipoTransaccionParameter = tipoTransaccion.HasValue ?
                new ObjectParameter("TipoTransaccion", tipoTransaccion) :
                new ObjectParameter("TipoTransaccion", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var oficinaParameter = oficina != null ?
                new ObjectParameter("Oficina", oficina) :
                new ObjectParameter("Oficina", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarMovimiento", tipoDocumentoParameter, documentoParameter, montoParameter, dbCreditoParameter, tipoTransaccionParameter, descripcionParameter, oficinaParameter);
        }
    
        public virtual int UpsertCliente(string nombres, string apellidos, Nullable<System.DateTime> fechaNacimiento, string sexo, string comentario, Nullable<int> tipoDocumento, string documento, Nullable<decimal> balance, Nullable<int> tipoTransaccion)
        {
            var nombresParameter = nombres != null ?
                new ObjectParameter("Nombres", nombres) :
                new ObjectParameter("Nombres", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("Apellidos", apellidos) :
                new ObjectParameter("Apellidos", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(string));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("Comentario", comentario) :
                new ObjectParameter("Comentario", typeof(string));
    
            var tipoDocumentoParameter = tipoDocumento.HasValue ?
                new ObjectParameter("TipoDocumento", tipoDocumento) :
                new ObjectParameter("TipoDocumento", typeof(int));
    
            var documentoParameter = documento != null ?
                new ObjectParameter("Documento", documento) :
                new ObjectParameter("Documento", typeof(string));
    
            var balanceParameter = balance.HasValue ?
                new ObjectParameter("Balance", balance) :
                new ObjectParameter("Balance", typeof(decimal));
    
            var tipoTransaccionParameter = tipoTransaccion.HasValue ?
                new ObjectParameter("TipoTransaccion", tipoTransaccion) :
                new ObjectParameter("TipoTransaccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpsertCliente", nombresParameter, apellidosParameter, fechaNacimientoParameter, sexoParameter, comentarioParameter, tipoDocumentoParameter, documentoParameter, balanceParameter, tipoTransaccionParameter);
        }
    }
}
